In [67]:
import torch

In [68]:
x = torch.tensor([1, 2, 3])
w = torch.tensor([1, 1, 1], requires_grad=True, dtype = torch.float32)
y = (x*w.T + 2).mean()
y.backward()

In [69]:
x.grad

In [70]:
w.grad

tensor([0.3333, 0.6667, 1.0000])

In [71]:
import torch.nn as nn
import torch.optim as optim

In [72]:
import seaborn as sns 
import matplotlib.pyplot as plt 

class NN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
    def forward(self, x):
        return self.fc2(self.fc1(x))
    def get_params(self):
        return [param for param in self.parameters()]
    
model = NN(2, 8, 1)
w_actual = torch.tensor([1, 2], dtype = torch.float32).reshape(2, 1)
x = torch.randn(100, 2)
y = torch.matmul(x, w_actual) + torch.randn(100, 1)/100

In [73]:
optimizer = optim.Adam(model.parameters(), lr = 0.01)
res = []
part = 20
x1, x2 = x[:part], x[part:]

res.extend([model(x1), model(x2)])

In [75]:
loss1 = ((y[:part] - res[0])**2).mean()
loss2 = ((y[part:] - res[1])**2).mean()

In [76]:
print(model.get_params())
optimizer.zero_grad()
loss1.backward()
loss2.backward()
optimizer.step()
print(model.get_params())

[Parameter containing:
tensor([[-0.0536,  0.5655],
        [-0.5516, -0.3982],
        [ 0.0339, -0.3195],
        [-0.0646,  0.3683],
        [-0.3319,  0.5971],
        [-0.5884,  0.5134],
        [-0.5329,  0.2987],
        [-0.2393,  0.0483]], requires_grad=True), Parameter containing:
tensor([-0.1547, -0.5307,  0.6067, -0.5109,  0.0016, -0.5031, -0.6535,  0.3284],
       requires_grad=True), Parameter containing:
tensor([[-0.0588,  0.1157, -0.2196,  0.1373, -0.3364,  0.1772, -0.2107,  0.3511]],
       requires_grad=True), Parameter containing:
tensor([-0.3335], requires_grad=True)]
[Parameter containing:
tensor([[-0.0636,  0.5555],
        [-0.5416, -0.3882],
        [ 0.0239, -0.3295],
        [-0.0546,  0.3783],
        [-0.3419,  0.5871],
        [-0.5784,  0.5234],
        [-0.5429,  0.2887],
        [-0.2293,  0.0583]], requires_grad=True), Parameter containing:
tensor([-0.1647, -0.5207,  0.5967, -0.5009, -0.0084, -0.4931, -0.6635,  0.3384],
       requires_grad=True), Parame